### ISSUE TITLE
Re: Commented scripts

### ISSUE THREAD

**Issue by sthurner11** [FRAMverse/coding-practices#3]
Currently, the guide says "When a script is likely to be re-used (e.g. not a one-off analysis), create a commented version with instructions on use. This should be stored somewhere accessible."

I would encourage that all scripts which will be reviewed by co-managers be commented with instructions on use, even if it is a one off analysis, so that it is easily understood.

**Comment by Ty-WDFW** [comment]
I think the spirit of this is "one-off analysis (that won't me shared)." Any collaboration should have those instructions and a description of what the script is doing, we'll make that distinction in the text.

**Comment by cbedwards-dfw** [comment]
Addressed with add/content.

**Comment by cbedwards-dfw** [comment]
Addressed with Add/content merge.
