### ISSUE TITLE
re: Sharing via zip folders

### ISSUE THREAD

**Issue by sthurner11** [FRAMverse/coding-practices#4]
just a note that there have been a number of issues sharing with zip folders between agencies over the years (both due to data size, especially when containing a database) and different security settings. I don't have a good alternative, but.... a thought haha

Also as a big fan of R projects, just a comment that I have had issues connecting to FRAM databases using framrsquared when in an rproject. Still not sure why, but, if other folks have issues with this just a PSA that this practice could have hiccups haha

**Comment by Ty-WDFW** [comment]
This is a great suggestion that we didn't think about that's always a pain. Regarding the framrsquared problems if you're able to reproduce the errors you can just open an issue over at FRAMverse/framrsquared. I've never had that issue, but I'm also the creator of the package and know exactly how it works.
