### ISSUE TITLE
re: version control

### ISSUE THREAD

**Issue by sthurner11** [FRAMverse/coding-practices#5]
Would suggest consistency in version naming -- I don't see us getting completely away from emailing versions of things anytime soon unfortunately...

**Comment by Ty-WDFW** [comment]
I agree, Excel and emails are going to be the primary mode of data communication for the foreseeable future. The github part is more for internal, WDFW, development of software while documenting the process for our collaborators to contribute or comment. We're 100% not trying to push github on anyone else, that would be unreasonable - we'll make that clear in the text.

**Comment by sthurner11** [comment]
I didn't think you were pushing anything! I more so meant that it would be nice to have 'best practices' for file version naming when sharing with folks i.e. Filename_date_editorinitials or something.

**Comment by cbedwards-dfw** [comment]
I'm down to include best practices for file version naming, although it does seem like that's less coding practices and more "Tech team practices"? I wonder if we should rename the final product to be a bit broader?

**Comment by cbedwards-dfw** [comment]
(In particular, I'd love if our non-coding collaborators had consistent file names)

**Comment by cbedwards-dfw** [comment]
Resolved when merging add/noncoding; see new "Non-coding section" with the suggested file naming structure. (Also, let me know how you feel about the non-coding section, and/or if you have more to add to it).

**Comment by sthurner11** [comment]
This looks good to me -- nice idea to add spreadsheet best practices. If I think of anything I will add an issue, haha.
